[2024-02-01T12:57:08.449+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:08.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:57:08.504+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:08.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:09.063+0000] {processor.py:840} INFO - DAG(s) 'your_dag_name' retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:10.284+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.282+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:your_dag_name
[2024-02-01T12:57:10.359+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.358+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:your_dag_name
[2024-02-01T12:57:10.440+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.439+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:your_dag_name
[2024-02-01T12:57:10.444+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.443+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-01T12:57:10.542+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.542+0000] {dag.py:3058} INFO - Creating ORM DAG for your_dag_name
[2024-02-01T12:57:10.650+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:10.648+0000] {dag.py:3823} INFO - Setting next_dagrun for your_dag_name to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-02-01T12:57:10.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 2.484 seconds
[2024-02-01T12:57:41.408+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:41.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:57:41.414+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:41.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:41.449+0000] {processor.py:840} INFO - DAG(s) 'your_dag_name' retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:57:41.498+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:41.498+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-01T12:57:41.567+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:57:41.566+0000] {dag.py:3823} INFO - Setting next_dagrun for your_dag_name to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-02-01T12:57:41.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.262 seconds
[2024-02-01T12:58:12.069+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:12.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:58:12.073+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:12.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:12.114+0000] {processor.py:840} INFO - DAG(s) 'your_dag_name' retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:12.163+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:12.162+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-01T12:58:12.201+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:12.201+0000] {dag.py:3823} INFO - Setting next_dagrun for your_dag_name to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-02-01T12:58:12.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.232 seconds
[2024-02-01T12:58:25.732+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:25.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:58:25.737+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:25.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:25.788+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:25.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T12:58:25.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:25.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.116 seconds
[2024-02-01T12:58:56.442+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:56.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:58:56.448+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:56.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:56.475+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:58:56.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T12:58:56.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:58:56.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.092 seconds
[2024-02-01T12:59:27.534+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:27.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:59:27.537+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:59:27.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:27.560+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:59:27.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T12:59:27.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:27.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.097 seconds
[2024-02-01T12:59:37.982+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:37.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T12:59:37.987+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:59:37.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:38.081+0000] {logging_mixin.py:188} INFO - [2024-02-01T12:59:38.070+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T12:59:38.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T12:59:38.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.217 seconds
[2024-02-01T13:00:09.114+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:09.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:00:09.117+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:00:09.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:09.150+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:00:09.142+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T13:00:09.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:09.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.091 seconds
[2024-02-01T13:00:40.075+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:40.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:00:40.085+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:00:40.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:40.139+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:00:40.132+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T13:00:40.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:00:40.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.141 seconds
[2024-02-01T13:01:11.616+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:11.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:01:11.632+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:01:11.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:11.835+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:01:11.786+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T13:01:11.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:12.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.498 seconds
[2024-02-01T13:01:43.148+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:43.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:01:43.153+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:01:43.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:43.198+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:01:43.187+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T13:01:43.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:01:43.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.138 seconds
[2024-02-01T13:02:13.582+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:13.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:02:13.612+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:02:13.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:13.699+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:02:13.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 2, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-02-01T13:02:13.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:13.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.395 seconds
[2024-02-01T13:02:43.924+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:43.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:02:43.931+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:02:43.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:44.016+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:02:44.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 15, in <module>
    dag = DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 557, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2024-02-01T13:02:44.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:02:44.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.169 seconds
[2024-02-01T13:03:14.989+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:14.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:03:14.993+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:03:14.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:15.038+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:03:15.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 15, in <module>
    dag = DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 557, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2024-02-01T13:03:15.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:15.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.153 seconds
[2024-02-01T13:03:45.977+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:45.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_postgres_dag.py for tasks to queue
[2024-02-01T13:03:45.980+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:03:45.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:46.002+0000] {logging_mixin.py:188} INFO - [2024-02-01T13:03:45.998+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_postgres_dag.py", line 15, in <module>
    dag = DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 557, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2024-02-01T13:03:46.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_postgres_dag.py
[2024-02-01T13:03:46.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_postgres_dag.py took 0.071 seconds
